---
# This playbook demonstrates a installing the httpd webserver
- hosts: all
  remote_user: root
  gather_facts: false
  become: true

  tasks:
  - name: Installing HTTPD
    yum:
      name: httpd
      state: latest

  - name: Copy over sample index.html page
    copy:
      src: files/index.html
      dest: /var/www/html/index.html

  - name: Start httpd service
    service:
      name: httpd
      state: started