---
  - name: Terminate instances
    hosts: localhost
    gather_facts: False
    connection: local
    tasks:
      - name: Terminate instances that were previously launched
        ec2:
          state: 'absent'
          instance_ids: '{{ ec2.instance_ids }}'